### ISSUE TITLE
Undefined symbols for architecture arm64:   "_onUnityMessage", referenced from:

### ISSUE THREAD

**Issue by Frulko** [f111fei/react-native-unity-demo#11]
Hi, 
first I want to say thank you for this react-native plugin !
It could be a best plugin to combine react-native & Unity

I have a problem with the installation of your demo. 
First I had this issue : https://github.com/f111fei/react-native-unity-demo/issues/2
It solve my first problem but a second has arrived.

`Undefined symbols for architecture arm64:
  "_onUnityMessage", referenced from:`

I'm on Unity 2017.2.0f3 & XCode 9.3

Have you an idea ? 
Thanks a lot !

**Comment by f111fei** [comment]
https://github.com/f111fei/react-native-unity-demo/issues/10#issuecomment-393413062

**Comment by vpsantos** [comment]
I just updated my Unity to 2018.1.1f1 and now I have the same problem Frulko, it was working for an older version.

Any idea f111fei?

**Comment by f111fei** [comment]
I think `UnityMessageManager` is bad.

Try to delete [UnityMessageManager](https://github.com/f111fei/react-native-unity-demo/blob/master/unity/Cube/Assets/Scripts/UnityMessageManager.cs) from unity project.

And build again.

**Comment by vpsantos** [comment]
Unfortunately not, could you please try to run the demo on Unity 2018.1.f1?

**Comment by vpsantos** [comment]
Ok, I will update my Unity again, but is the message working for you on iOS?

**Comment by Frulko** [comment]
Hi, i found maybe a solution. 

I unlink and link the react-native plugin and it solve my issue

**Comment by edamazzio** [comment]
@Frulko I have the same issue. Do you mean to run react-native unlink react-native-unity-view and then react-native link react-native-unity-view?

**Comment by Frulko** [comment]
yes this is what I've done.

**Comment by JanOwiesniak** [comment]
> @Frulko I have the same issue. Do you mean to run
> `react-native unlink react-native-unity-view `
> and then
> `react-native link react-native-unity-view`
> ?

Relinking solved the problem for me.

**Comment by shariq93** [comment]
I resolved this issue by installing the library first and then reimport the project from unity.

**Comment by scottthoo** [comment]
> I resolved this issue by installing the library first and then reimport the project from unity.

Hi @shariq93, can you explain more in detail?

**Comment by shariq93** [comment]
@scottthoo yes my issue is also reolved thanks

**Comment by Tommy-Elliott** [comment]
I resolved this issue by changing my script code to reference the UnityMessageManager via a private property on the class (`private UnityMessageManager MessageManager { get; set; }`), populated in `Start` method, via `MessageManager = GetComponent<UnityMessageManager>();` instead of what it was using when I got this error: `UnityMessageManager.Instance`.  I'm pretty sure the place it couldn't handle the latter is within the handler function I attached to the `ARSession.stateChanged` event, because the other places I used `UnityMessageManager.Instance` tested fine on iPhone before I added the handler that used it.
